name: Publish node-chrome-java docker image to Puneet's repository
on:
  push:
    branches: [ master ]
    paths:
      - "node-chrome-java/dockerfile"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Build docker image
        run: |
          docker build . -f node-chrome-java/dockerfile --tag puneetpunj/node-chrome-java:latest
      - name: Docker push
        run: |
          docker push puneetpunj/node-chrome-java:latest
